FROM quay.io/odpi/egeria-platform:latest@sha256:4a00179aa3de62c8043199ce105c960e4e69d500adda2f187d04639c7813dc63

# Freshstart secrets are runtime-mounted from runtime-volumes/freshstart-platform-data/secrets.

