FROM quay.io/odpi/egeria-platform:latest@sha256:28335896bc992b110f4244488a4150910dd31a62ced91c11d24abe4c4d4e9ced

# Freshstart secrets are runtime-mounted from runtime-volumes/freshstart-platform-data/secrets.

