#
# These commands connect fs-metadata-store to a cohort called "workspacesCollaboration".
# They use IntelliJ's HTTP Client.
#
# Make sure that you set up a unique organization name in the "yourOrgName" variable to be sure your servers
# are correctly identified.
#
@baseURL=https://localhost:9443
@adminUserId=add user here
@adminPassword=add password here
@cohort=workspacesCollaboration
@yourOrgName=add your org name here

###
# =====================================================================================================================
# Manage the authentication token.  Run this request to create/refresh the token.

# @name Token (RequestBody)
POST {{baseURL}}/api/token
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "userId" : "{{adminUserId}}",
  "password" : "{{adminPassword}}"
}

> {% client.global.set("token", response.body); %}

###
# -------------------------
# View Server: fs-view-server
#
###
# @name Set organization name
# Set up the name of the organization that owns this server.
POST {{baseURL}}/open-metadata/admin-services/servers/fs-view-server/organization-name?name={{yourOrgName}}
Authorization: Bearer {{token}}

###
# -------------------------
# Engine Host: fs-engine-host
#
###
# @name Set organization name
# Set up the name of the organization that owns this server.
POST {{baseURL}}/open-metadata/admin-services/servers/fs-engine-host/organization-name?name={{yourOrgName}}
Authorization: Bearer {{token}}

###
# ---------------------------------------
# Integration Daemon: fs-integration-daemon
#
###
# @name Set organization name
# Set up the name of the organization that owns this server.
POST {{baseURL}}/open-metadata/admin-services/servers/fs-integration-daemon/organization-name?name={{yourOrgName}}
Authorization: Bearer {{token}}

# ---------------------------------------------
# Metadata Access Store: fs-metadata-store
#
###
# @name Set organization name
# Set up the name of the organization that owns this server.
POST {{baseURL}}/open-metadata/admin-services/servers/fs-metadata-store/organization-name?name={{yourOrgName}}
Authorization: Bearer {{token}}

###
# Add the server to the cohort.
POST {{baseURL}}/open-metadata/admin-services/servers/fs-metadata-store/cohorts/{{cohort}}
Authorization: Bearer {{token}}


###
# Restart the fs-metadata-store server on the OMAG Server Platform.
POST {{baseURL}}/open-metadata/platform-services/server-platform/servers/fs-metadata-store/instance
Authorization: Bearer {{token}}




###