#FROM quay.io/odpi/egeria-platform:latest
FROM docker.io/odpi/egeria-platform:latest@sha256:8a68820714a5785d7ed8151adcb0e356e11822fd1e5bbd95dbfd77394267f59a
# Quickstart now relies on runtime-mounted /deployments content and default image behavior.

