FROM docker.io/library/eclipse-temurin:21 AS build
WORKDIR /usr/src/app
COPY gradle gradle
COPY gradle.properties gradle.properties
COPY gradlew gradlew
COPY settings.gradle settings.gradle
COPY build.gradle build.gradle
COPY src ./src
RUN ./gradlew --no-daemon shadowJar

FROM docker.io/library/eclipse-temurin:24@sha256:7493205ffe6caa8074fa8a06a276bb1c5ac41d3dd0fd43a0db66d7f776e80b3e
WORKDIR /usr/src/app
COPY --from=build /usr/src/app/build/libs/openlineage-proxy-*.jar /usr/src/app
COPY proxy.dev.yml proxy.dev.yml
COPY docker/entrypoint.sh entrypoint.sh
EXPOSE 6000 6001
ENTRYPOINT ["/usr/src/app/entrypoint.sh"]
