# SPDX-License-Identifier: Apache-2.0
# Copyright Contributors to the Egeria project
FROM docker:29-cli@sha256:018edbc908e08fcc9dbf029c812c34251e9b4719e6f71ca0e5eae2a987d014ca
RUN apk add --no-cache curl jq
COPY watch-egeria.sh /watch-egeria.sh
RUN chmod +x /watch-egeria.sh
ENTRYPOINT ["/watch-egeria.sh"]
