# SPDX-License-Identifier: Apache-2.0
# Copyright Contributors to the Egeria project
FROM docker:29-cli@sha256:000bb62ff495f986c9f5578eb67cc2cb98b91138eda81d7762d5371eb8a497fe
RUN apk add --no-cache curl
COPY autoheal.sh /autoheal.sh
RUN chmod +x /autoheal.sh
ENTRYPOINT ["/autoheal.sh"]
