# SPDX-License-Identifier: Apache-2.0
# Copyright Contributors to the Egeria project
FROM docker:29-cli@sha256:3f4743208d2338c934d7b8bcfbe1bb54c0b2355c510ad5e0f31c0c4a54bd704e
RUN apk add --no-cache curl
COPY autoheal.sh /autoheal.sh
RUN chmod +x /autoheal.sh
ENTRYPOINT ["/autoheal.sh"]
