# SPDX-License-Identifier: Apache-2.0
# Copyright Contributors to the Egeria project.

# This build script corrects some permission issues needed to run
# on some enterprise k8s environments. see https://github.com/odpi/egeria-jupyter-notebooks/issues/9

# The published image tag is taken from the numerical version of
# our base image, and appended with the contents of .tag-append (file)
FROM quay.io/jupyter/scipy-notebook

RUN pip install --no-cache-dir 'pyegeria>=0.5.5.13'
RUN pip install --no-cache-dir 'rich'
RUN pip install --no-cache-dir 'unitycatalog'
RUN pip install --no-cache-dir 'pipx'
RUN pipx ensurepath
RUN pipx install pyegeria
RUN pipx ensurepath

RUN alias view_integ='view_integ_daemon_status --integ_url https://host.docker.internal:9443 --view_url https://host.docker.internal:9443'
RUN alias view_plat='view_platform_status --url https://host.docker.internal:9443'

RUN mkdir -p /home/jovyan/workspaces
RUN chmod +xrw /home/jovyan/workspaces
copy ../Start-Here.md /home/jovyan
#    && \
#    fix-permissions "${CONDA_DIR}" && \
#    fix-permissions "/home/${NB_USER}" \

#ENTRYPOINT ["jupyter","notebook"]
#
#CMD ["python3", "/config_coco_core.py"]
#USER root

# Needed to dynamically add the selected user on startup - see link below
#RUN chmod g+w /etc/passwd
#
#RUN chown -R $NB_UID:$NB_GID $HOME
#
## https://cloud.redhat.com/blog/jupyter-on-openshift-part-6-running-as-an-assigned-user-id
#RUN chgrp -Rf root /home/$NB_USER && chmod -Rf g+w /home/$NB_USER && chgrp -Rf root /opt/conda && chmod -Rf g+w /opt/conda
#
#USER 1000
