"""
SPDX-License-Identifier: Apache-2.0
Copyright Contributors to the ODPi Egeria project.

Bootstrap batches — discovers folders of Dr.Egeria documents under the
loading-bay's dr-egeria-inbox, and tracks an admin's live-editable selection
of which folders/files should run during (re)initialization after Egeria
has been wiped.

Design notes
------------
- Discovery, not registration: any folder dropped under dr-egeria-inbox
  shows up automatically. An optional `_batch.json` manifest in a folder
  gives it a friendlier display name/description, an explicit file order,
  and (optionally) a canary element for bootstrap_monitor_handler.py's
  auto-heal reset-detection. No manifest -> the folder name is used as-is,
  files run alphabetically, and it's manual/no-canary (a reasonable default
  for a folder someone just dropped in -- it won't silently auto-run).
- Selection state is a plain JSON file under ~/.pyegeria, NOT the demo_auth
  Postgres table used elsewhere in this app for admin-editable settings
  (obsidian_vault_url, reset_state, etc.) -- freshstart has no Postgres
  wired up at all (confirmed: egeria-freshstart.yaml has no DEMO_DB_* vars
  and isn't even on shared-infra's network), so a Postgres-backed store
  would silently break there. ~/.pyegeria is already the established
  pattern for this exact class of small persistent admin state --
  local_dashboards_handler.py's dashboard_sheets.json uses the identical
  shape (env-overridable path, mtime-based reload) and is mounted
  identically in both quickstart's and freshstart's compose files.
- dr-egeria-inbox itself is mounted read-only (see egeria-quickstart.yaml /
  egeria-freshstart.yaml, both `:ro` on the pyegeria-web service) --
  selection state can never live inside it.

Execution order
---------------
Within a folder: _batch.json's `files` list (if present) is the explicit
order. An entry may be a file, a file in a subfolder ("sub/x.md"), or a
whole subfolder ("sub/"), which expands in place to that subfolder's own
order (its own _batch.json, recursively). Anything NOT mentioned is
appended afterward -- unlisted .md files alphabetically, then unlisted
subfolders alphabetically -- and flagged with a validation warning when
the folder has a `files` list. `exclude` skips named files/subfolders;
README.md and plumbing/output folders (dr-egeria-outbox, logs, data, ...)
are always skipped unless named in `files`. No manifest -> alphabetical
files, then alphabetical subfolders. See _expand_folder. (Extra-root
batches -- see _EXTRA_BATCH_ROOTS -- are the one exception: their
manifest's `files` list is used as-is, with no auto-append and no
recursion, since that folder also holds unrelated source files.)

A subfolder that is itself another batch's root (an inbox symlink to a
nested folder) runs in that batch, not its parent; and within one run-all
or auto-heal pass each file runs at most once (see discover_batches).

Across folders: dr-egeria-inbox/_folder_order.json, if present, is a flat
JSON array of batch ids (folder names, or an extra-root's batch_id) giving
the order batches run in. Any batch not mentioned runs after the listed
ones, alphabetically by id -- same "explicit list, then alphabetical
remainder" rule as the per-folder file order, for consistency.
"""

import asyncio
import hashlib
import json
import os
import re
import time
from collections import deque
from dataclasses import dataclass
from pathlib import Path
from typing import Optional

from loguru import logger

# Folders that are inbox plumbing, not selectable batches.
_SKIP_DIRS = {"logs", ".ipynb_checkpoints", ".git", ".DS_Store"}

_INBOX_ROOT = Path(os.environ.get(
    "EGERIA_BOOTSTRAP_INBOX_ROOT", "/deployments/loading-bay/dr-egeria-inbox"
))

# A handful of core-portal seed docs live alongside the handler code itself
# (checked into the repo, generated by their own scripts -- e.g.
# gen_governance_metrics.py writes OVERVIEW_GOVERNANCE_METRICS.dr-egeria.md
# right here) rather than under the user-facing, folder-per-batch
# dr-egeria-inbox tree. Each entry here is (batch_id, folder). Unlike an
# inbox folder, a manifest is REQUIRED -- there's no safe default file list
# for a directory that also holds unrelated .py/.html source, so a missing
# _batch.json just means that extra batch doesn't register (see
# discover_batches). This list is deliberately short and hand-maintained;
# anything meant to be admin-droppable belongs under dr-egeria-inbox instead.
_EXTRA_BATCH_ROOTS = [
    ("overview-governance-metrics", Path(__file__).parent),
]


def _selection_store_path() -> str:
    return os.path.expanduser(
        os.getenv("PYEGERIA_BOOTSTRAP_STORE", "~/.pyegeria/bootstrap_batches.json")
    )


# Bootstrap/auto-heal activity (batch runs, heal attempts, timeouts) otherwise
# only ever reached docker logs -- gone the moment a container is recreated,
# which is exactly when you'd want to know what auto-heal did. Sink it into
# the same persisted ~/.pyegeria dir bootstrap_batches.json already lives in
# (mounted identically in both quickstart's and freshstart's compose files),
# filtered to just this feature's three modules so it doesn't become a
# second copy of the whole app's logs. Module-level code runs once per
# process (Python caches the import), so this only ever adds one sink.
_BOOTSTRAP_LOG_MODULES = {"bootstrap_batches", "bootstrap_admin_handler", "bootstrap_monitor_handler"}
_bootstrap_log_path = os.path.expanduser(
    os.getenv("PYEGERIA_BOOTSTRAP_LOG", "~/.pyegeria/bootstrap.log")
)
os.makedirs(os.path.dirname(_bootstrap_log_path), exist_ok=True)
logger.add(
    _bootstrap_log_path,
    filter=lambda r: r["name"] in _BOOTSTRAP_LOG_MODULES,
    rotation="5 MB",
    retention=5,
    level="INFO",
    enqueue=True,
)


def tail_log(lines: int = 200) -> list[str]:
    """Last `lines` lines of bootstrap.log, oldest first -- for the admin
    page's Recent Activity panel. Only reads the current (post-rotation)
    file, not retained rotated copies; that's plenty for "what just
    happened", which is all this panel is for. Missing file (nothing
    logged yet) -> empty list, not an error."""
    if not os.path.exists(_bootstrap_log_path):
        return []
    try:
        with open(_bootstrap_log_path, encoding="utf-8", errors="replace") as f:
            return [line.rstrip("\n") for line in deque(f, maxlen=lines)]
    except Exception as exc:  # noqa: BLE001
        logger.warning(f"bootstrap_batches: could not read log {_bootstrap_log_path}: {exc}")
        return []


# dr_egeria itself (the `dr_egeria --process` subprocess run_batch() shells
# out to, and the FastAPI process's own pyegeria calls) logs its own,
# much more detailed activity -- every command, validation, and traceback
# -- to pyegeria.log via loguru, independently of bootstrap.log above (which
# only ever gets the one-line-per-file summary this module itself logs).
# That's where the actual "why did dr_egeria fail" detail lives (e.g. a
# server-side "not a valid metadata value" validation error, or a Python
# traceback from a failed API call) but nothing in the admin UI surfaced it
# before -- you had to shell into the container and grep it by hand. This
# tails it filtered to ERROR/WARNING lines only: the file routinely runs
# into the hundreds of thousands of lines (every DRY RUN validation and
# HTTP request is its own INFO line), so an unfiltered tail would mostly
# show noise. ANSI colour codes (loguru colourises this sink) are stripped
# since they render literally in a plain <pre> block.
_dr_egeria_log_path = os.path.join(
    os.environ.get("PYEGERIA_LOG_DIRECTORY", os.path.join(os.path.dirname(__file__), "logs")),
    "pyegeria.log",
)
_ANSI_RE = re.compile(r"\x1b\[[0-9;]*m")


def tail_dr_egeria_issues(lines: int = 200) -> list[str]:
    """Last `lines` ERROR/WARNING lines from pyegeria.log -- dr_egeria's own
    detailed activity log, not bootstrap.log's one-line-per-file summary.
    Missing file -> empty list, not an error (matches tail_log())."""
    if not os.path.exists(_dr_egeria_log_path):
        return []
    try:
        with open(_dr_egeria_log_path, encoding="utf-8", errors="replace") as f:
            matches = (line.rstrip("\n") for line in f if " | ERROR " in line or " | WARNING " in line)
            return [_ANSI_RE.sub("", line) for line in deque(matches, maxlen=lines)]
    except Exception as exc:  # noqa: BLE001
        logger.warning(f"bootstrap_batches: could not read log {_dr_egeria_log_path}: {exc}")
        return []


# path -> (mtime, dict)
_selection_cache: dict[str, tuple[float, dict]] = {}


def load_selection() -> dict:
    """{"<folder_name>": {"enabled": bool, "files": {"<filename>": bool}}}"""
    path = _selection_store_path()
    if not os.path.exists(path):
        return {}
    mtime = os.path.getmtime(path)
    cached = _selection_cache.get(path)
    if cached and cached[0] == mtime:
        return cached[1]
    try:
        with open(path, encoding="utf-8") as f:
            data = json.load(f)
    except Exception as exc:  # noqa: BLE001
        logger.warning(f"bootstrap_batches: could not read selection store {path}: {exc}")
        data = {}
    _selection_cache[path] = (mtime, data)
    return data


def save_selection(selection: dict) -> None:
    path = _selection_store_path()
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w", encoding="utf-8") as f:
        json.dump(selection, f, indent=2, sort_keys=True)
    _selection_cache.pop(path, None)


def _read_manifest(folder: Path, warnings: Optional[list] = None) -> dict:
    manifest_path = folder / "_batch.json"
    if not manifest_path.exists():
        return {}
    try:
        with open(manifest_path, encoding="utf-8") as f:
            return json.load(f)
    except Exception as exc:  # noqa: BLE001
        logger.warning(f"bootstrap_batches: bad manifest {manifest_path}: {exc}")
        if warnings is not None:
            warnings.append(_warn("error", f"{manifest_path.name} could not be read ({exc}) -- "
                                           "folder fell back to alphabetical order"))
        return {}


# ---------------------------------------------------------------------------
# Recursive discovery
#
# A batch's subfolders run inline, at their place in the parent's order --
# coco-workbooks/1. coco-data-hub's README orders files and subfolders
# together (step 4 is extending-the-systems-inventory/, step 7 is
# strategic-digital-products/), so a `files` entry may name a subfolder
# ("strategic-digital-products/") as well as a file, or a file inside one
# ("mapping-the-systems/egeria-implementation.md"). A named subfolder expands
# to its own order, using its own _batch.json if it has one, recursively.
#
# Unlisted content is still appended (so a newly dropped file or folder shows
# up without anyone editing a manifest): unlisted top-level .md files
# alphabetically, then unlisted subfolders alphabetically. When the manifest
# HAS a `files` list, each appended item also gets a validation warning --
# its position was never chosen, only defaulted.
#
# Never descended into unless named explicitly in `files`: the plumbing/
# output folders below. dr-egeria-outbox in particular holds dr_egeria's
# *processed* copies of earlier runs -- real commands, so re-running them
# would replay stale content. README.md is skipped the same way (prose, not
# commands); `exclude` in _batch.json adds more of either.
_SKIP_SUBDIRS = {"logs", ".ipynb_checkpoints", "__pycache__", "dr-egeria-outbox",
                 "egeria-outbox", "data", "templates"}
_SKIP_FILES = {"readme.md"}


def _warn(level: str, message: str) -> dict:
    return {"level": level, "message": message}


@dataclass
class _ExpandCtx:
    other_roots: dict          # resolved Path -> batch id, for every OTHER registered batch
    seen_files: set            # resolved file paths already placed in this batch
    userids: dict              # relative path -> Egeria userid to run it as (only when one is declared)
    visited_dirs: set          # resolved dirs already expanded (symlink-cycle guard)
    warnings: list


def _is_runnable_md(p: Path) -> bool:
    return p.is_file() and p.suffix.lower() == ".md"


def _entry_parts(entry) -> tuple[Optional[str], Optional[str]]:
    """A `files` entry is a plain string, or {"file": ..., "userid": ...}."""
    if isinstance(entry, str):
        return entry, None
    if isinstance(entry, dict) and isinstance(entry.get("file"), str):
        userid = entry.get("userid")
        return entry["file"], (str(userid) if userid else None)
    return None, None


def _expand_folder(folder: Path, prefix: str, ctx: _ExpandCtx,
                   inherited_user: Optional[str] = None) -> list[str]:
    """Execution-ordered paths (relative to the batch root, '/'-separated)
    for `folder` and everything under it. See the block comment above.

    Run-as identity (ctx.userids): the nearest declaration wins -- the
    file's own `files` entry, then the `userid` of the manifest in the
    file's folder, then whatever the parent folders passed down (a parent's
    entry for this subfolder, or the parent's own `userid`). Nothing
    declared -> no entry, and dr_egeria uses its default identity."""
    real = folder.resolve()
    if real in ctx.visited_dirs:
        ctx.warnings.append(_warn("warning", f"{prefix or './'} is reachable twice (symlink loop?) -- expanded once"))
        return []
    ctx.visited_dirs.add(real)

    manifest = _read_manifest(folder, ctx.warnings)
    folder_user = str(manifest["userid"]) if manifest.get("userid") else inherited_user
    listed = manifest.get("files") or []
    excluded = {str(x).rstrip("/") for x in (manifest.get("exclude") or [])}
    out: list[str] = []
    placed_top: set[str] = set()   # direct children named in `files`, excluded from the remainder pass

    def add_file(p: Path, rel: str, user: Optional[str]) -> None:
        rp = p.resolve()
        if rp in ctx.seen_files:
            return  # already placed earlier in this batch (e.g. listed directly AND via its folder)
        ctx.seen_files.add(rp)
        out.append(rel)
        if user:
            ctx.userids[rel] = user

    def add_dir(p: Path, rel: str, user: Optional[str]) -> None:
        owner = ctx.other_roots.get(p.resolve())
        if owner is not None:
            ctx.warnings.append(_warn("info", f"{rel}/ runs as its own batch '{owner}', not inline here"))
            return
        out.extend(_expand_folder(p, rel + "/", ctx, user))

    for entry in listed:
        raw, entry_user = _entry_parts(entry)
        if raw is None:
            ctx.warnings.append(_warn("warning", f"_batch.json in {prefix or './'} has an unreadable files "
                                                 f"entry {entry!r} -- expected a name or "
                                                 '{"file": ..., "userid": ...}; skipped'))
            continue
        name = raw.rstrip("/")
        if name in excluded:
            continue
        p = folder / name
        user = entry_user or folder_user
        if "/" not in name:
            placed_top.add(name)  # a nested entry ("sub/x.md") leaves the rest of sub/ to the remainder pass
        if p.is_dir():
            add_dir(p, prefix + name, user)
        elif _is_runnable_md(p):
            add_file(p, prefix + name, user)
        else:
            ctx.warnings.append(_warn("warning", f"_batch.json in {prefix or './'} lists {entry!r}, "
                                                 "which isn't there -- skipped"))

    has_order = bool(listed)
    try:
        children = sorted(folder.iterdir(), key=lambda c: c.name)
    except OSError as exc:
        ctx.warnings.append(_warn("error", f"could not list {prefix or './'}: {exc}"))
        return out

    remaining_files = [c for c in children
                       if _is_runnable_md(c) and c.name not in placed_top and c.name not in excluded
                       and c.name.lower() not in _SKIP_FILES]
    remaining_dirs = [c for c in children
                      if c.is_dir() and c.name not in placed_top and c.name not in excluded
                      and c.name not in _SKIP_SUBDIRS and not c.name.startswith(".")]
    for c in remaining_files:
        if has_order:
            ctx.warnings.append(_warn("warning", f"{prefix}{c.name} isn't in _batch.json's files list -- "
                                                 "runs after the listed files, alphabetically"))
        add_file(c, prefix + c.name, folder_user)
    for c in remaining_dirs:
        before = len(out)
        add_dir(c, prefix + c.name, folder_user)
        if has_order and len(out) > before:
            ctx.warnings.append(_warn("warning", f"{prefix}{c.name}/ isn't in _batch.json's files list -- "
                                                 "runs after the listed files, alphabetically"))
    return out


# Dr.Egeria command detection, for the "this file contains no commands"
# validation warning. Uses pyegeria's own command list (the same one
# dr_egeria matches headings against) when it's importable; otherwise a
# verb-only heading regex. Either way it's advisory -- nothing is skipped
# because of it.
_HEADING_RE = re.compile(r"^#{1,6}\s+(.+?)\s*#*\s*$", re.M)
_VERB_RE = re.compile(r"^(Create|Update|Link|Unlink|Attach|Detach|Add|Remove|Classify|Declassify|Reclassify|"
                      r"Setup|Set|Assign|Cancel|Clear|Import|Initiate|Publish|Run|View|Provenance)\b", re.I)
_command_names: Optional[set] = None
_command_count_cache: dict[str, tuple[int, int]] = {}   # path -> (mtime_ns, count)


def _known_commands() -> set:
    global _command_names
    if _command_names is None:
        try:
            from md_processing.md_processing_utils import md_processing_constants as mpc
            if not mpc.command_list:
                mpc.load_commands()
            _command_names = {c.lower() for c in mpc.command_list}
        except Exception as exc:  # noqa: BLE001
            logger.debug(f"bootstrap_batches: pyegeria command list unavailable, using verb regex: {exc}")
            _command_names = set()
    return _command_names


def count_commands(path: Path) -> Optional[int]:
    """Dr.Egeria command headings in `path`, or None if it couldn't be read."""
    try:
        mtime = path.stat().st_mtime_ns
    except OSError:
        return None
    key = str(path)
    cached = _command_count_cache.get(key)
    if cached and cached[0] == mtime:
        return cached[1]
    try:
        text = path.read_text(encoding="utf-8", errors="replace")
    except OSError:
        return None
    known = _known_commands()
    headings = _HEADING_RE.findall(text)
    if known:
        count = sum(1 for h in headings if h.lower() in known)
    else:
        count = sum(1 for h in headings if _VERB_RE.match(h))
    _command_count_cache[key] = (mtime, count)
    return count


# ---------------------------------------------------------------------------
# Run ledger -- per-file record of the last time the Portal itself ran a file
# successfully, and what the file's content was then. Lets the admin panel
# show which files are new or changed since they were last run (a file added
# to an already-loaded batch never triggers auto-heal, whose only signal is
# the canary). Keyed by resolved path, so a file reachable through two
# symlinks is one entry.
#
# Advisory only: it never causes a file to be skipped. After an Egeria wipe
# the ledger still says "ran", and that's the point of auto-heal re-running
# it anyway. "no_record" means "not run through the Portal since the ledger
# existed", NOT "never loaded" -- files loaded from a notebook, Obsidian or
# the CLI, or before this ledger shipped, are all no_record.
def _ledger_path() -> str:
    return os.path.expanduser(os.getenv("PYEGERIA_BOOTSTRAP_LEDGER", "~/.pyegeria/bootstrap_ledger.json"))


_sha_cache: dict[str, tuple[int, int, str]] = {}   # path -> (mtime_ns, size, sha256)


def _file_sha(path: Path) -> Optional[str]:
    try:
        st = path.stat()
    except OSError:
        return None
    key = str(path)
    cached = _sha_cache.get(key)
    if cached and cached[0] == st.st_mtime_ns and cached[1] == st.st_size:
        return cached[2]
    h = hashlib.sha256()
    try:
        with open(path, "rb") as f:
            for chunk in iter(lambda: f.read(1 << 16), b""):
                h.update(chunk)
    except OSError:
        return None
    digest = h.hexdigest()
    _sha_cache[key] = (st.st_mtime_ns, st.st_size, digest)
    return digest


def _load_ledger() -> dict:
    path = _ledger_path()
    if not os.path.exists(path):
        return {}
    try:
        with open(path, encoding="utf-8") as f:
            data = json.load(f)
        return data if isinstance(data, dict) else {}
    except Exception as exc:  # noqa: BLE001
        logger.warning(f"bootstrap_batches: could not read run ledger {path}: {exc}")
        return {}


def record_run(doc: Path) -> None:
    """Note a successful `dr_egeria --process` of `doc`. Sync, no awaits --
    the read-modify-write can't interleave with another caller in the event
    loop."""
    real = doc.resolve()
    ledger = _load_ledger()
    ledger[str(real)] = {"sha256": _file_sha(real), "lastRunAt": time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime())}
    path = _ledger_path()
    try:
        os.makedirs(os.path.dirname(path), exist_ok=True)
        tmp = path + ".tmp"
        with open(tmp, "w", encoding="utf-8") as f:
            json.dump(ledger, f, indent=2, sort_keys=True)
        os.replace(tmp, path)
    except Exception as exc:  # noqa: BLE001
        logger.warning(f"bootstrap_batches: could not write run ledger {path}: {exc}")


def _ledger_state(doc: Path, ledger: dict) -> dict:
    entry = ledger.get(str(doc.resolve()))
    if not entry:
        return {"runState": "no_record", "lastRunAt": None}
    current = _file_sha(doc)
    changed = current is not None and entry.get("sha256") not in (None, current)
    return {"runState": "changed" if changed else "current", "lastRunAt": entry.get("lastRunAt")}


def _ordered_inbox_files(entry: Path, other_roots: dict, warnings: list) -> tuple[list[str], dict]:
    ctx = _ExpandCtx(other_roots=other_roots, seen_files=set(), userids={},
                     visited_dirs=set(), warnings=warnings)
    return _expand_folder(entry, "", ctx), ctx.userids


# ---------------------------------------------------------------------------
# Run-as identity. A manifest can say which Egeria user each file is loaded
# as (the coco-workbooks READMEs load each file as the persona who owns it,
# so definitions are attributed to them), but never a password: that comes
# from EGERIA_BOOTSTRAP_PASSWORD_<USERID> (upper-cased), then
# EGERIA_USER_PASSWORD, then "secret" -- the same fallback the rest of this
# app's handlers use for the demo personas.
def _password_for(userid: str) -> str:
    return (os.environ.get(f"EGERIA_BOOTSTRAP_PASSWORD_{userid.upper()}")
            or os.environ.get("EGERIA_USER_PASSWORD")
            or "secret")


def dr_egeria_command(doc: Path, userid: Optional[str]) -> list[str]:
    """argv for processing `doc`, as `userid` when one is declared (otherwise
    dr_egeria's own default identity -- EGERIA_USER, or its built-in default)."""
    cmd = ["dr_egeria", "--process", str(doc)]
    if userid:
        cmd += ["--userid", userid, "--user_pass", _password_for(userid)]
    return cmd


def _read_folder_order() -> list[str]:
    order_path = _INBOX_ROOT / "_folder_order.json"
    if not order_path.exists():
        return []
    try:
        with open(order_path, encoding="utf-8") as f:
            data = json.load(f)
        return [str(x) for x in data] if isinstance(data, list) else []
    except Exception as exc:  # noqa: BLE001
        logger.warning(f"bootstrap_batches: bad folder order file {order_path}: {exc}")
        return []


def _apply_order(items: list[dict], order: list[str], key: str) -> list[dict]:
    """Explicit `order` list first (only entries actually present, in that
    sequence), then everything else alphabetically by `key`."""
    order_index = {name: i for i, name in enumerate(order)}
    listed = sorted((it for it in items if it[key] in order_index),
                     key=lambda it: order_index[it[key]])
    rest = sorted((it for it in items if it[key] not in order_index),
                   key=lambda it: it[key])
    return listed + rest


def _batch_dict(batch_id: str, folder: Path, manifest: dict, files: list[str], warnings: list,
                userids: Optional[dict] = None) -> dict:
    return {
        "id":             batch_id,
        "displayName":    manifest.get("displayName") or batch_id,
        "description":    manifest.get("description") or "",
        "canary":         manifest.get("canary"),
        "files":          files,
        "path":           str(folder),
        "defaultEnabled": bool(manifest.get("defaultEnabled", False)),
        "idempotent":     bool(manifest.get("idempotent", True)),
        "warnings":       warnings,
        "userids":        userids or {},
    }


def _discover_once(inbox_dirs: list[Path], owners: dict) -> list[dict]:
    batches = []
    for entry in inbox_dirs:
        warnings: list = []
        manifest = _read_manifest(entry, warnings)
        other_roots = {r: bid for r, bid in owners.items() if bid != entry.name}
        files, userids = _ordered_inbox_files(entry, other_roots, warnings)
        if not files:
            continue
        batches.append(_batch_dict(entry.name, entry, manifest, files, warnings, userids))

    for batch_id, folder in _EXTRA_BATCH_ROOTS:
        manifest = _read_manifest(folder)
        if not manifest.get("files"):
            continue  # no manifest (or no files listed) -- this extra batch doesn't register
        files, userids = [], {}
        for entry in manifest["files"]:
            name, entry_user = _entry_parts(entry)
            if name and (folder / name).exists():
                files.append(name)
                if entry_user or manifest.get("userid"):
                    userids[name] = entry_user or str(manifest["userid"])
        if not files:
            continue
        batches.append(_batch_dict(batch_id, folder, manifest, files, [], userids))
    return batches


def discover_batches() -> list[dict]:
    """Scan dr-egeria-inbox for folders (each becomes a batch, including its
    subfolders -- see _expand_folder), plus any _EXTRA_BATCH_ROOTS, ordered
    per _folder_order.json if present. Returns
    [{id, displayName, description, canary, files, path, defaultEnabled,
      idempotent, warnings}] -- `files` are paths relative to `path`.

    Double-run prevention, at discovery time: a subfolder that is itself
    some other batch's root (an inbox symlink pointing at a nested folder,
    e.g. "Coco - 1. Data Field Naming" -> 1. coco-data-hub/data-field-naming)
    belongs to that batch, and its parent skips it. Only batches that
    actually register (have files) claim their folder, hence the loop: an
    empty batch's folder is released back to its parent. Within a batch,
    a file reachable twice is placed once. Across batches, any remaining
    overlap gets a warning here and is skipped at run time (see
    run_all_enabled / bootstrap_monitor_handler.check_and_heal_all).

    `idempotent` (manifest field, default True) -- whether re-running this
    batch's files against an already-seeded target is known-safe. Default
    True keeps existing manifests' behavior unchanged; set explicitly to
    False for a batch containing a command that creates a relationship/
    record with no pre-existence check (confirmed the hard way: `Link
    Governance Results` in md_processing/v2/governance.py calls
    `_async_link_governance_results` unconditionally, unlike e.g. `Link
    Report to Dashboard Sheet` in dashboard_sheet.py, which matches on
    `ref == report_name` and replaces in place -- genuinely idempotent,
    despite looking like the same class of command). Auto-heal is
    unaffected by this flag (it only ever runs a batch whose canary is
    missing, never a present one) -- this exists purely to gate the admin
    panel's manual "Run Now"/"Run All Enabled" actions, which otherwise
    run unconditionally. See bootstrap_admin_handler.py."""
    if not _INBOX_ROOT.is_dir():
        logger.warning(f"bootstrap_batches: inbox root not found: {_INBOX_ROOT}")
        inbox_dirs = []
    else:
        inbox_dirs = [e for e in sorted(_INBOX_ROOT.iterdir())
                      if e.is_dir() and e.name not in _SKIP_DIRS and not e.name.startswith(".")]

    owners = {e.resolve(): e.name for e in inbox_dirs}
    batches: list[dict] = []
    for _ in range(4):  # converges in 1-2 passes; bounded in case of pathological symlinks
        batches = _discover_once(inbox_dirs, owners)
        registered = {b["id"] for b in batches}
        narrowed = {r: bid for r, bid in owners.items() if bid in registered}
        if narrowed == owners:
            break
        owners = narrowed

    batches = _apply_order(batches, _read_folder_order(), "id")

    # Cross-batch overlap (e.g. two inbox symlinks to the same folder, or a
    # manifest naming a file inside another batch's folder). Reported, not
    # removed -- which copy runs depends on which batches are enabled, so
    # the run-time dedupe decides.
    first_seen: dict[str, str] = {}
    for b in batches:
        base = Path(b["path"])
        for rel in b["files"]:
            real = str((base / rel).resolve())
            if real in first_seen:
                b["warnings"].append(_warn("warning", f"{rel} also runs in batch '{first_seen[real]}' -- "
                                                      "it runs once per pass, in whichever comes first"))
            else:
                first_seen[real] = b["id"]
    return batches


def batches_with_selection() -> list[dict]:
    """Discovered batches merged with saved selection state, run ledger and
    validation. A folder with no saved selection yet falls back to its
    manifest's defaultEnabled (False if unset/no manifest) -- so a plain
    admin-droppable folder stays off until someone opts in, while a
    core-portal family whose manifest sets defaultEnabled:true keeps
    auto-healing out of the box, with no seed file needed on a fresh
    deploy. Files within an enabled batch default to True."""
    selection = load_selection()
    ledger = _load_ledger()
    result = []
    for batch in discover_batches():
        sel = selection.get(batch["id"], {})
        file_sel = sel.get("files", {})
        base = Path(batch["path"])
        files = []
        warnings = list(batch["warnings"])
        for f in batch["files"]:
            doc = base / f
            commands = count_commands(doc)
            if commands == 0:
                warnings.append(_warn("warning", f"{f} contains no Dr.Egeria commands -- if it's prose, "
                                                 "add it to _batch.json's exclude list"))
            files.append({"name": f, "enabled": bool(file_sel.get(f, True)),
                          "commands": commands, "userid": batch["userids"].get(f),
                          **_ledger_state(doc, ledger)})
        result.append({
            **batch,
            "enabled": bool(sel.get("enabled", batch.get("defaultEnabled", False))),
            "files": files,
            "warnings": warnings,
        })
    return result


def enabled_batches() -> list[dict]:
    """Batches (with only their enabled files) selected to run at
    (re)initialization -- what bootstrap_monitor_handler.py's auto-heal and
    the admin "run selected now" action both consume."""
    out = []
    for batch in batches_with_selection():
        if not batch["enabled"]:
            continue
        files = [f["name"] for f in batch["files"] if f["enabled"]]
        if files:
            out.append({**batch, "files": files})
    return out


# Per-file cap on a `dr_egeria --process` run, and the subprocesses currently
# in flight so the timeout/cancellation paths below can actually terminate them.
#
# 900s (15 min), was a hardcoded 300s. This is the same fix already applied to
# bootstrap_monitor_handler.py's heal path on 2026-08-28 (_DR_EGERIA_TIMEOUT)
# that never got mirrored here, so the admin-triggered "run selected"/
# "(re)initialize now" path kept the old cap: coco-workbooks/0.
# data-governance-program/employee-glossary.md (6.1k lines, 86 Create Glossary
# Term commands) reliably exceeds 300s and was the only file in a full run to
# fail (confirmed live 2026-08-29, 17/18 files ok). Every Dr.Egeria doc is
# upsert-safe, so generous headroom costs nothing -- a longer wait only avoids
# giving up on genuinely slow (not stuck) files.
#
# And, as in that module, a timeout used to leave the `dr_egeria` child running
# orphaned: asyncio.wait_for()'s TimeoutError just abandons the await and sends
# no signal to the OS process. The orphan keeps writing to Egeria, invisible to
# this module -- in the 2026-08-29 log employee-glossary.md "timed out" at
# 13:07:45 while its process was still going as the batch moved on to the next
# file 5s later. Re-running a batch in that window is what produced duplicate
# elements in the Design Patterns incident; see the _active_procs comment in
# bootstrap_monitor_handler.py for the full write-up.
# "duplicate" = reached again later in the same pass and deliberately not
# re-run (see run_batch's `seen`) -- not a failure.
_SUCCESS_STATUSES = {"ok", "duplicate"}
_BATCH_TIMEOUT = int(os.environ.get("BOOTSTRAP_BATCH_TIMEOUT_SECONDS", "900"))
_active_procs: set = set()


async def _kill_proc(proc) -> None:
    try:
        proc.kill()
        await proc.wait()
    except ProcessLookupError:
        pass  # already exited
    except Exception as exc:  # noqa: BLE001
        logger.debug(f"bootstrap batches: error killing orphaned dr_egeria process: {exc}")


async def run_batch(batch: dict, timeout_seconds: int = _BATCH_TIMEOUT,
                    seen: Optional[set] = None) -> list[dict]:
    """Run a batch's files in order via `dr_egeria --process`. Every
    Dr.Egeria doc is upsert-safe, so this is always safe to re-run. Unlike
    bootstrap_monitor_handler.py's _heal_family (which stops at the first
    failure since it's healing a known-good sequence), this keeps going and
    reports per-file results -- an admin manually running a batch wants to
    see everything that happened, not just where it stopped.

    Every file's outcome (and a completion summary) is also written to
    bootstrap.log -- previously only the *start* of a manual run was logged
    (see run_batch_now in bootstrap_admin_handler.py), so an admin who saw
    "Run failed" in the UI and missed/lost the HTTP response had no way to
    tell what happened short of shelling into the container. The full
    dr_egeria output (validation errors, tracebacks) still isn't here --
    that lives in pyegeria.log, surfaced separately by
    tail_dr_egeria_issues() below -- this is just enough to know which
    file(s) failed and why, from the admin page itself.

    `seen` (resolved paths) is shared across the batches of one pass by
    run_all_enabled: a file that already ran earlier in the pass -- because
    two batches reach the same file, see discover_batches -- is skipped
    rather than run twice. Successful runs are noted in the run ledger."""
    results = []
    folder = Path(batch["path"])
    if seen is None:
        seen = set()
    for filename in batch["files"]:
        doc = folder / filename
        if not doc.exists():
            results.append({"file": filename, "status": "skipped", "message": "file not found"})
            logger.warning(f"bootstrap batches: {batch['id']!r} — {filename}: skipped (file not found)")
            continue
        real = doc.resolve()
        if real in seen:
            results.append({"file": filename, "status": "duplicate", "message": "already ran earlier in this pass"})
            logger.info(f"bootstrap batches: {batch['id']!r} — {filename}: skipped (already ran earlier in this pass)")
            continue
        seen.add(real)
        proc = None
        try:
            proc = await asyncio.create_subprocess_exec(
                *dr_egeria_command(doc, batch.get("userids", {}).get(filename)),
                stdout=asyncio.subprocess.PIPE, stderr=asyncio.subprocess.STDOUT,
            )
            _active_procs.add(proc)
            stdout, _ = await asyncio.wait_for(proc.communicate(), timeout=timeout_seconds)
            tail = stdout.decode(errors="replace")[-800:] if stdout else ""
            if proc.returncode == 0:
                results.append({"file": filename, "status": "ok", "message": tail})
                record_run(doc)
                logger.info(f"bootstrap batches: {batch['id']!r} — {filename}: ok")
            else:
                results.append({"file": filename, "status": "failed", "message": tail})
                logger.warning(
                    f"bootstrap batches: {batch['id']!r} — {filename}: failed "
                    f"(exit {proc.returncode}) — {_one_line(tail)}"
                )
        except asyncio.TimeoutError:
            # Kill the child before moving on -- an abandoned await leaves it
            # running and still writing to Egeria (see _active_procs above).
            if proc is not None:
                await _kill_proc(proc)
            results.append({"file": filename, "status": "failed",
                            "message": f"timed out after {timeout_seconds}s"})
            logger.warning(f"bootstrap batches: {batch['id']!r} — {filename}: timed out after {timeout_seconds}s")
        except asyncio.CancelledError:
            # App reload/shutdown cancelled the background run task -- kill the
            # child before letting the cancellation propagate, same reason as
            # the timeout branch above.
            if proc is not None:
                await _kill_proc(proc)
            raise
        except Exception as exc:  # noqa: BLE001
            results.append({"file": filename, "status": "failed", "message": str(exc)})
            logger.warning(f"bootstrap batches: {batch['id']!r} — {filename}: failed — {exc}")
        finally:
            if proc is not None:
                _active_procs.discard(proc)

    ok = sum(1 for r in results if r["status"] in _SUCCESS_STATUSES)
    failed = [r["file"] for r in results if r["status"] == "failed"]
    skipped = [r["file"] for r in results if r["status"] == "skipped"]
    summary = f"bootstrap batches: {batch['id']!r} finished — {ok}/{len(results)} files ok"
    if failed:
        summary += f"; failed: {', '.join(failed)}"
    if skipped:
        summary += f"; skipped: {', '.join(skipped)}"
    logger.log("WARNING" if failed else "INFO", summary)
    return results


def _one_line(text: str, max_len: int = 200) -> str:
    """Collapse a (possibly multi-line, possibly empty) dr_egeria output
    tail into one short line for a bootstrap.log entry -- the full text is
    still in the per-file `message` the HTTP response returns, and the full
    dr_egeria log is available via tail_dr_egeria_issues()."""
    one_line = " ".join(text.split())
    return (one_line[:max_len] + "…") if len(one_line) > max_len else (one_line or "(no output)")


async def run_all_enabled(timeout_seconds: int = _BATCH_TIMEOUT) -> list[dict]:
    """Run every enabled batch, in discover_batches' order (folder order
    file, then alphabetical), each with its own enabled files in file
    order. This is the "(re)initialize now" action -- the counterpart to
    bootstrap_monitor_handler.py's automatic canary-triggered heal, for
    when an admin wants to force it without waiting for a reset to be
    detected. Returns one entry per batch: {batch, results}."""
    out = []
    seen: set = set()
    for batch in enabled_batches():
        out.append({"batch": batch["id"], "results": await run_batch(batch, timeout_seconds, seen)})
    ok = sum(1 for run in out for r in run["results"] if r["status"] in _SUCCESS_STATUSES)
    total = sum(len(run["results"]) for run in out)
    logger.log(
        "INFO" if ok == total else "WARNING",
        f"bootstrap batches: run-all finished — {len(out)} batches, {ok}/{total} files ok",
    )
    return out


# ---------------------------------------------------------------------------
# Background run + poll -- a manual run of even one moderately-sized batch
# routinely takes longer than Apache's ProxyPass timeout (5 min,
# proxy-locations.conf), which drops the browser's connection long before
# `await run_batch(...)`/`run_all_enabled()` finish -- the backend keeps
# working (nothing cancels it), but the admin sees a bare "Run failed" with
# no way to tell it actually succeeded short of the Activity Log. Same
# non-blocking cold-start/poll shape as operations_handler.py's
# _get_server_report_cached (see that module's design-notes comment) --
# start the run as a background asyncio Task and return immediately, let
# the client poll for the result instead of holding the connection open.
#
# Unlike that cache, there's no TTL/staleness here -- a run either hasn't
# started, is running, or is done with one final result. And unlike
# bootstrap_monitor_handler.py's heal path, the *run state* here is
# in-memory only and is lost on a reload; a client polling a key that's
# vanished gets "not_found" and should surface that as an interruption,
# not hang forever. (The dr_egeria subprocess itself IS now killed on a
# reload mid-run -- see _kill_proc/_active_procs above; it used to be left
# orphaned, which is what allowed two concurrent runs of the same file.)
RUN_ALL_KEY = "__run_all__"  # batch ids are folder names -- never collides with this


@dataclass
class _RunState:
    status: str  # "running" | "done"
    success: Optional[bool] = None
    results: Optional[list[dict]] = None  # single-batch shape
    runs: Optional[list[dict]] = None     # run-all shape (list of {batch, results})


_run_state: dict[str, _RunState] = {}
_run_tasks: dict[str, "asyncio.Task"] = {}


def run_status(key: str) -> dict:
    """Poll the outcome of a background run started via start_background().
    `key` is a batch id, or RUN_ALL_KEY for the run-all-enabled action."""
    state = _run_state.get(key)
    if state is None:
        return {"status": "not_found"}
    if state.status == "running":
        return {"status": "running"}
    out = {"status": "done", "success": state.success}
    if state.results is not None:
        out["results"] = state.results
    if state.runs is not None:
        out["runs"] = state.runs
    return out


async def _run_in_background(key: str, coro) -> None:
    try:
        result = await coro
        if key == RUN_ALL_KEY:
            ok = all(r["status"] in _SUCCESS_STATUSES for run in result for r in run["results"])
            _run_state[key] = _RunState(status="done", success=ok, runs=result)
        else:
            ok = all(r["status"] in _SUCCESS_STATUSES for r in result)
            _run_state[key] = _RunState(status="done", success=ok, results=result)
    except Exception as exc:  # noqa: BLE001
        logger.warning(f"bootstrap batches: background run {key!r} crashed: {exc}")
        _run_state[key] = _RunState(
            status="done", success=False,
            **({"runs": []} if key == RUN_ALL_KEY else {"results": [{"file": "*", "status": "failed", "message": str(exc)}]}),
        )
    finally:
        _run_tasks.pop(key, None)


def start_background(key: str, coro) -> bool:
    """Start `coro` (an already-called run_batch(...)/run_all_enabled(...))
    as a background task under `key`, unless one is already in flight for
    that key. Returns True if this call actually started it, False if a
    run for this key was already running (the caller should just let the
    client poll the existing one rather than starting a second)."""
    existing = _run_tasks.get(key)
    if existing is not None and not existing.done():
        coro.close()  # never awaited -- avoid a "coroutine was never awaited" warning
        return False
    _run_state[key] = _RunState(status="running")
    _run_tasks[key] = asyncio.get_event_loop().create_task(_run_in_background(key, coro))
    return True
