"""
SPDX-License-Identifier: Apache-2.0
Copyright Contributors to the ODPi Egeria project.

Bootstrap batches — discovers folders of Dr.Egeria documents under the
loading-bay's dr-egeria-inbox, and tracks an admin's live-editable selection
of which folders/files should run during (re)initialization after Egeria
has been wiped.

Design notes
------------
- Discovery, not registration: any folder dropped under dr-egeria-inbox
  shows up automatically. An optional `_batch.json` manifest in a folder
  gives it a friendlier display name/description, an explicit file order,
  and (optionally) a canary element for bootstrap_monitor_handler.py's
  auto-heal reset-detection. No manifest -> the folder name is used as-is,
  files run alphabetically, and it's manual/no-canary (a reasonable default
  for a folder someone just dropped in -- it won't silently auto-run).
- Selection state is a plain JSON file under ~/.pyegeria, NOT the demo_auth
  Postgres table used elsewhere in this app for admin-editable settings
  (obsidian_vault_url, reset_state, etc.) -- freshstart has no Postgres
  wired up at all (confirmed: egeria-freshstart.yaml has no DEMO_DB_* vars
  and isn't even on shared-infra's network), so a Postgres-backed store
  would silently break there. ~/.pyegeria is already the established
  pattern for this exact class of small persistent admin state --
  local_dashboards_handler.py's dashboard_sheets.json uses the identical
  shape (env-overridable path, mtime-based reload) and is mounted
  identically in both quickstart's and freshstart's compose files.
- dr-egeria-inbox itself is mounted read-only (see egeria-quickstart.yaml /
  egeria-freshstart.yaml, both `:ro` on the pyegeria-web service) --
  selection state can never live inside it.

Execution order
---------------
Within a folder: _batch.json's `files` list (if present) is the explicit
order for those files; any other .md file in the folder NOT mentioned
there is appended afterward, alphabetically. No manifest -> pure
alphabetical. (Extra-root batches -- see _EXTRA_BATCH_ROOTS -- are the one
exception: their manifest's `files` list is used as-is, with no auto-append
of "other .md files in the folder", since that folder also holds unrelated
source files.)

Across folders: dr-egeria-inbox/_folder_order.json, if present, is a flat
JSON array of batch ids (folder names, or an extra-root's batch_id) giving
the order batches run in. Any batch not mentioned runs after the listed
ones, alphabetically by id -- same "explicit list, then alphabetical
remainder" rule as the per-folder file order, for consistency.
"""

import json
import os
import time
from pathlib import Path
from typing import Optional

from loguru import logger

# Folders that are inbox plumbing, not selectable batches.
_SKIP_DIRS = {"logs", ".ipynb_checkpoints", ".git", ".DS_Store"}

_INBOX_ROOT = Path(os.environ.get(
    "EGERIA_BOOTSTRAP_INBOX_ROOT", "/deployments/loading-bay/dr-egeria-inbox"
))

# A handful of core-portal seed docs live alongside the handler code itself
# (checked into the repo, generated by their own scripts -- e.g.
# gen_governance_metrics.py writes OVERVIEW_GOVERNANCE_METRICS.dr-egeria.md
# right here) rather than under the user-facing, folder-per-batch
# dr-egeria-inbox tree. Each entry here is (batch_id, folder). Unlike an
# inbox folder, a manifest is REQUIRED -- there's no safe default file list
# for a directory that also holds unrelated .py/.html source, so a missing
# _batch.json just means that extra batch doesn't register (see
# discover_batches). This list is deliberately short and hand-maintained;
# anything meant to be admin-droppable belongs under dr-egeria-inbox instead.
_EXTRA_BATCH_ROOTS = [
    ("overview-governance-metrics", Path(__file__).parent),
]


def _selection_store_path() -> str:
    return os.path.expanduser(
        os.getenv("PYEGERIA_BOOTSTRAP_STORE", "~/.pyegeria/bootstrap_batches.json")
    )


# Bootstrap/auto-heal activity (batch runs, heal attempts, timeouts) otherwise
# only ever reached docker logs -- gone the moment a container is recreated,
# which is exactly when you'd want to know what auto-heal did. Sink it into
# the same persisted ~/.pyegeria dir bootstrap_batches.json already lives in
# (mounted identically in both quickstart's and freshstart's compose files),
# filtered to just this feature's three modules so it doesn't become a
# second copy of the whole app's logs. Module-level code runs once per
# process (Python caches the import), so this only ever adds one sink.
_BOOTSTRAP_LOG_MODULES = {"bootstrap_batches", "bootstrap_admin_handler", "bootstrap_monitor_handler"}
_bootstrap_log_path = os.path.expanduser(
    os.getenv("PYEGERIA_BOOTSTRAP_LOG", "~/.pyegeria/bootstrap.log")
)
os.makedirs(os.path.dirname(_bootstrap_log_path), exist_ok=True)
logger.add(
    _bootstrap_log_path,
    filter=lambda r: r["name"] in _BOOTSTRAP_LOG_MODULES,
    rotation="5 MB",
    retention=5,
    level="INFO",
    enqueue=True,
)


# path -> (mtime, dict)
_selection_cache: dict[str, tuple[float, dict]] = {}


def load_selection() -> dict:
    """{"<folder_name>": {"enabled": bool, "files": {"<filename>": bool}}}"""
    path = _selection_store_path()
    if not os.path.exists(path):
        return {}
    mtime = os.path.getmtime(path)
    cached = _selection_cache.get(path)
    if cached and cached[0] == mtime:
        return cached[1]
    try:
        with open(path, encoding="utf-8") as f:
            data = json.load(f)
    except Exception as exc:  # noqa: BLE001
        logger.warning(f"bootstrap_batches: could not read selection store {path}: {exc}")
        data = {}
    _selection_cache[path] = (mtime, data)
    return data


def save_selection(selection: dict) -> None:
    path = _selection_store_path()
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w", encoding="utf-8") as f:
        json.dump(selection, f, indent=2, sort_keys=True)
    _selection_cache.pop(path, None)


def _read_manifest(folder: Path) -> dict:
    manifest_path = folder / "_batch.json"
    if not manifest_path.exists():
        return {}
    try:
        with open(manifest_path, encoding="utf-8") as f:
            return json.load(f)
    except Exception as exc:  # noqa: BLE001
        logger.warning(f"bootstrap_batches: bad manifest {manifest_path}: {exc}")
        return {}


def _ordered_inbox_files(entry: Path, manifest: dict) -> list[str]:
    """Files in a dr-egeria-inbox subfolder, in execution order: the
    manifest's explicit `files` list first (in that order, minus any that
    no longer exist -- a stale reference, not an error), then any other
    .md file in the folder it doesn't mention, alphabetically. No manifest
    (or an empty `files` list) -> pure alphabetical, same as before this
    ordering feature existed."""
    all_md = sorted(p.name for p in entry.iterdir()
                     if p.is_file() and p.suffix.lower() == ".md" and p.name != "_batch.json")
    listed = [f for f in (manifest.get("files") or []) if f in all_md]
    remaining = [f for f in all_md if f not in listed]
    return listed + remaining


def _read_folder_order() -> list[str]:
    order_path = _INBOX_ROOT / "_folder_order.json"
    if not order_path.exists():
        return []
    try:
        with open(order_path, encoding="utf-8") as f:
            data = json.load(f)
        return [str(x) for x in data] if isinstance(data, list) else []
    except Exception as exc:  # noqa: BLE001
        logger.warning(f"bootstrap_batches: bad folder order file {order_path}: {exc}")
        return []


def _apply_order(items: list[dict], order: list[str], key: str) -> list[dict]:
    """Explicit `order` list first (only entries actually present, in that
    sequence), then everything else alphabetically by `key`."""
    order_index = {name: i for i, name in enumerate(order)}
    listed = sorted((it for it in items if it[key] in order_index),
                     key=lambda it: order_index[it[key]])
    rest = sorted((it for it in items if it[key] not in order_index),
                   key=lambda it: it[key])
    return listed + rest


def discover_batches() -> list[dict]:
    """Scan dr-egeria-inbox for folders (each becomes a batch), plus any
    _EXTRA_BATCH_ROOTS, ordered per _folder_order.json if present. Returns
    [{id, displayName, description, canary, files, defaultEnabled, idempotent}].

    `idempotent` (manifest field, default True) -- whether re-running this
    batch's files against an already-seeded target is known-safe. Default
    True keeps existing manifests' behavior unchanged; set explicitly to
    False for a batch containing a command that creates a relationship/
    record with no pre-existence check (confirmed the hard way: `Link
    Governance Results` in md_processing/v2/governance.py calls
    `_async_link_governance_results` unconditionally, unlike e.g. `Link
    Report to Dashboard Sheet` in dashboard_sheet.py, which matches on
    `ref == report_name` and replaces in place -- genuinely idempotent,
    despite looking like the same class of command). Auto-heal is
    unaffected by this flag (it only ever runs a batch whose canary is
    missing, never a present one) -- this exists purely to gate the admin
    panel's manual "Run Now"/"Run All Enabled" actions, which otherwise
    run unconditionally. See bootstrap_admin_handler.py."""
    batches = []

    if _INBOX_ROOT.is_dir():
        for entry in sorted(_INBOX_ROOT.iterdir()):
            if not entry.is_dir() or entry.name in _SKIP_DIRS or entry.name.startswith("."):
                continue
            manifest = _read_manifest(entry)
            files = _ordered_inbox_files(entry, manifest)
            if not files:
                continue
            batches.append({
                "id":             entry.name,
                "displayName":    manifest.get("displayName") or entry.name,
                "description":    manifest.get("description") or "",
                "canary":         manifest.get("canary"),
                "files":          files,
                "path":           str(entry),
                "defaultEnabled": bool(manifest.get("defaultEnabled", False)),
                "idempotent":     bool(manifest.get("idempotent", True)),
            })
    else:
        logger.warning(f"bootstrap_batches: inbox root not found: {_INBOX_ROOT}")

    for batch_id, folder in _EXTRA_BATCH_ROOTS:
        manifest = _read_manifest(folder)
        if not manifest.get("files"):
            continue  # no manifest (or no files listed) -- this extra batch doesn't register
        files = [f for f in manifest["files"] if (folder / f).exists()]
        if not files:
            continue
        batches.append({
            "id":             batch_id,
            "displayName":    manifest.get("displayName") or batch_id,
            "description":    manifest.get("description") or "",
            "canary":         manifest.get("canary"),
            "files":          files,
            "path":           str(folder),
            "defaultEnabled": bool(manifest.get("defaultEnabled", False)),
            "idempotent":     bool(manifest.get("idempotent", True)),
        })

    return _apply_order(batches, _read_folder_order(), "id")


def batches_with_selection() -> list[dict]:
    """Discovered batches merged with saved selection state. A folder with
    no saved selection yet falls back to its manifest's defaultEnabled
    (False if unset/no manifest) -- so a plain admin-droppable folder stays
    off until someone opts in, while a core-portal family whose manifest
    sets defaultEnabled:true keeps auto-healing out of the box, with no
    seed file needed on a fresh deploy. Files within an enabled batch
    default to True."""
    selection = load_selection()
    result = []
    for batch in discover_batches():
        sel = selection.get(batch["id"], {})
        file_sel = sel.get("files", {})
        result.append({
            **batch,
            "enabled": bool(sel.get("enabled", batch.get("defaultEnabled", False))),
            "files": [
                {"name": f, "enabled": bool(file_sel.get(f, True))}
                for f in batch["files"]
            ],
        })
    return result


def enabled_batches() -> list[dict]:
    """Batches (with only their enabled files) selected to run at
    (re)initialization -- what bootstrap_monitor_handler.py's auto-heal and
    the admin "run selected now" action both consume."""
    out = []
    for batch in batches_with_selection():
        if not batch["enabled"]:
            continue
        files = [f["name"] for f in batch["files"] if f["enabled"]]
        if files:
            out.append({**batch, "files": files})
    return out


async def run_batch(batch: dict, timeout_seconds: int = 300) -> list[dict]:
    """Run a batch's files in order via `dr_egeria --process`. Every
    Dr.Egeria doc is upsert-safe, so this is always safe to re-run. Unlike
    bootstrap_monitor_handler.py's _heal_family (which stops at the first
    failure since it's healing a known-good sequence), this keeps going and
    reports per-file results -- an admin manually running a batch wants to
    see everything that happened, not just where it stopped."""
    import asyncio

    results = []
    folder = Path(batch["path"])
    for filename in batch["files"]:
        doc = folder / filename
        if not doc.exists():
            results.append({"file": filename, "status": "skipped", "message": "file not found"})
            continue
        try:
            proc = await asyncio.create_subprocess_exec(
                "dr_egeria", "--process", str(doc),
                stdout=asyncio.subprocess.PIPE, stderr=asyncio.subprocess.STDOUT,
            )
            stdout, _ = await asyncio.wait_for(proc.communicate(), timeout=timeout_seconds)
            tail = stdout.decode(errors="replace")[-800:] if stdout else ""
            if proc.returncode == 0:
                results.append({"file": filename, "status": "ok", "message": tail})
            else:
                results.append({"file": filename, "status": "failed", "message": tail})
        except asyncio.TimeoutError:
            results.append({"file": filename, "status": "failed", "message": "timed out"})
        except Exception as exc:  # noqa: BLE001
            results.append({"file": filename, "status": "failed", "message": str(exc)})
    return results


async def run_all_enabled(timeout_seconds: int = 300) -> list[dict]:
    """Run every enabled batch, in discover_batches' order (folder order
    file, then alphabetical), each with its own enabled files in file
    order. This is the "(re)initialize now" action -- the counterpart to
    bootstrap_monitor_handler.py's automatic canary-triggered heal, for
    when an admin wants to force it without waiting for a reset to be
    detected. Returns one entry per batch: {batch, results}."""
    out = []
    for batch in enabled_batches():
        out.append({"batch": batch["id"], "results": await run_batch(batch, timeout_seconds)})
    return out
